package com.gythtglxt.dataobject;

import java.util.Date;

public class ChineseMedicineDO extends ChineseMedicineDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_chinese_medicine.NAME
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_chinese_medicine.ALIAS
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    private String alias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_chinese_medicine.CLASSIFICATION
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    private String classification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_chinese_medicine.HARVESTING
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    private String harvesting;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_chinese_medicine.TASTE
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    private String taste;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_chinese_medicine.MER_TROPISM
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    private String merTropism;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_chinese_medicine.GOVERNANCE
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    private String governance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_chinese_medicine.USAGE
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    private String usage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_chinese_medicine.STATUS
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_chinese_medicine.USER_CODE
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    private String userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_chinese_medicine.CREATER
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_chinese_medicine.itemCreateAt
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    private Date itemcreateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_chinese_medicine.UPDATER
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_chinese_medicine.itemUpdateAt
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    private Date itemupdateat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_chinese_medicine.NAME
     *
     * @return the value of tb_natmeha_chinese_medicine.NAME
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_chinese_medicine.NAME
     *
     * @param name the value for tb_natmeha_chinese_medicine.NAME
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_chinese_medicine.ALIAS
     *
     * @return the value of tb_natmeha_chinese_medicine.ALIAS
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_chinese_medicine.ALIAS
     *
     * @param alias the value for tb_natmeha_chinese_medicine.ALIAS
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_chinese_medicine.CLASSIFICATION
     *
     * @return the value of tb_natmeha_chinese_medicine.CLASSIFICATION
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    public String getClassification() {
        return classification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_chinese_medicine.CLASSIFICATION
     *
     * @param classification the value for tb_natmeha_chinese_medicine.CLASSIFICATION
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    public void setClassification(String classification) {
        this.classification = classification == null ? null : classification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_chinese_medicine.HARVESTING
     *
     * @return the value of tb_natmeha_chinese_medicine.HARVESTING
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    public String getHarvesting() {
        return harvesting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_chinese_medicine.HARVESTING
     *
     * @param harvesting the value for tb_natmeha_chinese_medicine.HARVESTING
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    public void setHarvesting(String harvesting) {
        this.harvesting = harvesting == null ? null : harvesting.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_chinese_medicine.TASTE
     *
     * @return the value of tb_natmeha_chinese_medicine.TASTE
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    public String getTaste() {
        return taste;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_chinese_medicine.TASTE
     *
     * @param taste the value for tb_natmeha_chinese_medicine.TASTE
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    public void setTaste(String taste) {
        this.taste = taste == null ? null : taste.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_chinese_medicine.MER_TROPISM
     *
     * @return the value of tb_natmeha_chinese_medicine.MER_TROPISM
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    public String getMerTropism() {
        return merTropism;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_chinese_medicine.MER_TROPISM
     *
     * @param merTropism the value for tb_natmeha_chinese_medicine.MER_TROPISM
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    public void setMerTropism(String merTropism) {
        this.merTropism = merTropism == null ? null : merTropism.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_chinese_medicine.GOVERNANCE
     *
     * @return the value of tb_natmeha_chinese_medicine.GOVERNANCE
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    public String getGovernance() {
        return governance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_chinese_medicine.GOVERNANCE
     *
     * @param governance the value for tb_natmeha_chinese_medicine.GOVERNANCE
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    public void setGovernance(String governance) {
        this.governance = governance == null ? null : governance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_chinese_medicine.USAGE
     *
     * @return the value of tb_natmeha_chinese_medicine.USAGE
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    public String getUsage() {
        return usage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_chinese_medicine.USAGE
     *
     * @param usage the value for tb_natmeha_chinese_medicine.USAGE
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    public void setUsage(String usage) {
        this.usage = usage == null ? null : usage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_chinese_medicine.STATUS
     *
     * @return the value of tb_natmeha_chinese_medicine.STATUS
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_chinese_medicine.STATUS
     *
     * @param status the value for tb_natmeha_chinese_medicine.STATUS
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_chinese_medicine.USER_CODE
     *
     * @return the value of tb_natmeha_chinese_medicine.USER_CODE
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_chinese_medicine.USER_CODE
     *
     * @param userCode the value for tb_natmeha_chinese_medicine.USER_CODE
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_chinese_medicine.CREATER
     *
     * @return the value of tb_natmeha_chinese_medicine.CREATER
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_chinese_medicine.CREATER
     *
     * @param creater the value for tb_natmeha_chinese_medicine.CREATER
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_chinese_medicine.itemCreateAt
     *
     * @return the value of tb_natmeha_chinese_medicine.itemCreateAt
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    public Date getItemcreateat() {
        return itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_chinese_medicine.itemCreateAt
     *
     * @param itemcreateat the value for tb_natmeha_chinese_medicine.itemCreateAt
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    public void setItemcreateat(Date itemcreateat) {
        this.itemcreateat = itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_chinese_medicine.UPDATER
     *
     * @return the value of tb_natmeha_chinese_medicine.UPDATER
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_chinese_medicine.UPDATER
     *
     * @param updater the value for tb_natmeha_chinese_medicine.UPDATER
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_chinese_medicine.itemUpdateAt
     *
     * @return the value of tb_natmeha_chinese_medicine.itemUpdateAt
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    public Date getItemupdateat() {
        return itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_chinese_medicine.itemUpdateAt
     *
     * @param itemupdateat the value for tb_natmeha_chinese_medicine.itemUpdateAt
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    public void setItemupdateat(Date itemupdateat) {
        this.itemupdateat = itemupdateat;
    }
}