package com.gythtglxt.dataobject;

import java.util.Date;

public class DoctorDO extends DoctorDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_doctor.DOCTOR_NAME
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String doctorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_doctor.DOCTOR_TITLE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String doctorTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_doctor.DOCTOR_TREATMENT
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String doctorTreatment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_doctor.DOCTOR_SORCE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private Double doctorSorce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_doctor.DEPT_CODE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String deptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_doctor.NUM_TYPE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String numType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_doctor.USER_CODE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_doctor.CREATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_doctor.itemCreateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private Date itemcreateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_doctor.UPDATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_doctor.itemUpdateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private Date itemupdateat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_doctor.DOCTOR_NAME
     *
     * @return the value of tb_natmeha_doctor.DOCTOR_NAME
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getDoctorName() {
        return doctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_doctor.DOCTOR_NAME
     *
     * @param doctorName the value for tb_natmeha_doctor.DOCTOR_NAME
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName == null ? null : doctorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_doctor.DOCTOR_TITLE
     *
     * @return the value of tb_natmeha_doctor.DOCTOR_TITLE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getDoctorTitle() {
        return doctorTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_doctor.DOCTOR_TITLE
     *
     * @param doctorTitle the value for tb_natmeha_doctor.DOCTOR_TITLE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setDoctorTitle(String doctorTitle) {
        this.doctorTitle = doctorTitle == null ? null : doctorTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_doctor.DOCTOR_TREATMENT
     *
     * @return the value of tb_natmeha_doctor.DOCTOR_TREATMENT
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getDoctorTreatment() {
        return doctorTreatment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_doctor.DOCTOR_TREATMENT
     *
     * @param doctorTreatment the value for tb_natmeha_doctor.DOCTOR_TREATMENT
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setDoctorTreatment(String doctorTreatment) {
        this.doctorTreatment = doctorTreatment == null ? null : doctorTreatment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_doctor.DOCTOR_SORCE
     *
     * @return the value of tb_natmeha_doctor.DOCTOR_SORCE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public Double getDoctorSorce() {
        return doctorSorce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_doctor.DOCTOR_SORCE
     *
     * @param doctorSorce the value for tb_natmeha_doctor.DOCTOR_SORCE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setDoctorSorce(Double doctorSorce) {
        this.doctorSorce = doctorSorce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_doctor.DEPT_CODE
     *
     * @return the value of tb_natmeha_doctor.DEPT_CODE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_doctor.DEPT_CODE
     *
     * @param deptCode the value for tb_natmeha_doctor.DEPT_CODE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_doctor.NUM_TYPE
     *
     * @return the value of tb_natmeha_doctor.NUM_TYPE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getNumType() {
        return numType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_doctor.NUM_TYPE
     *
     * @param numType the value for tb_natmeha_doctor.NUM_TYPE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setNumType(String numType) {
        this.numType = numType == null ? null : numType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_doctor.USER_CODE
     *
     * @return the value of tb_natmeha_doctor.USER_CODE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_doctor.USER_CODE
     *
     * @param userCode the value for tb_natmeha_doctor.USER_CODE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_doctor.CREATER
     *
     * @return the value of tb_natmeha_doctor.CREATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_doctor.CREATER
     *
     * @param creater the value for tb_natmeha_doctor.CREATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_doctor.itemCreateAt
     *
     * @return the value of tb_natmeha_doctor.itemCreateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public Date getItemcreateat() {
        return itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_doctor.itemCreateAt
     *
     * @param itemcreateat the value for tb_natmeha_doctor.itemCreateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setItemcreateat(Date itemcreateat) {
        this.itemcreateat = itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_doctor.UPDATER
     *
     * @return the value of tb_natmeha_doctor.UPDATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_doctor.UPDATER
     *
     * @param updater the value for tb_natmeha_doctor.UPDATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_doctor.itemUpdateAt
     *
     * @return the value of tb_natmeha_doctor.itemUpdateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public Date getItemupdateat() {
        return itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_doctor.itemUpdateAt
     *
     * @param itemupdateat the value for tb_natmeha_doctor.itemUpdateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setItemupdateat(Date itemupdateat) {
        this.itemupdateat = itemupdateat;
    }
}