package com.gythtglxt.dataobject;

import java.util.Date;

public class HospitalDO extends HospitalDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_hospital.HOSPITAL_NAME
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String hospitalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_hospital.HOSPITAL_LEVEL
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String hospitalLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_hospital.HOSPITAL_BOOKING
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private Integer hospitalBooking;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_hospital.HOSPITAL_SOURCE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private Double hospitalSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_hospital.HOSPITAL_DISTANCE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private Integer hospitalDistance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_hospital.HOSPITAL_PHONE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String hospitalPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_hospital.HOSPITAL_PRO
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String hospitalPro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_hospital.HOSPITAL_CITY
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String hospitalCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_hospital.HOSPITAL_COUNTRY
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String hospitalCountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_hospital.HOSPITAL_ADRESS
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String hospitalAdress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_hospital.CREATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_hospital.itemCreateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private Date itemcreateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_hospital.UPDATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_hospital.itemUpdateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private Date itemupdateat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_hospital.HOSPITAL_NAME
     *
     * @return the value of tb_natmeha_hospital.HOSPITAL_NAME
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getHospitalName() {
        return hospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_hospital.HOSPITAL_NAME
     *
     * @param hospitalName the value for tb_natmeha_hospital.HOSPITAL_NAME
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName == null ? null : hospitalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_hospital.HOSPITAL_LEVEL
     *
     * @return the value of tb_natmeha_hospital.HOSPITAL_LEVEL
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getHospitalLevel() {
        return hospitalLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_hospital.HOSPITAL_LEVEL
     *
     * @param hospitalLevel the value for tb_natmeha_hospital.HOSPITAL_LEVEL
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setHospitalLevel(String hospitalLevel) {
        this.hospitalLevel = hospitalLevel == null ? null : hospitalLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_hospital.HOSPITAL_BOOKING
     *
     * @return the value of tb_natmeha_hospital.HOSPITAL_BOOKING
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public Integer getHospitalBooking() {
        return hospitalBooking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_hospital.HOSPITAL_BOOKING
     *
     * @param hospitalBooking the value for tb_natmeha_hospital.HOSPITAL_BOOKING
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setHospitalBooking(Integer hospitalBooking) {
        this.hospitalBooking = hospitalBooking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_hospital.HOSPITAL_SOURCE
     *
     * @return the value of tb_natmeha_hospital.HOSPITAL_SOURCE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public Double getHospitalSource() {
        return hospitalSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_hospital.HOSPITAL_SOURCE
     *
     * @param hospitalSource the value for tb_natmeha_hospital.HOSPITAL_SOURCE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setHospitalSource(Double hospitalSource) {
        this.hospitalSource = hospitalSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_hospital.HOSPITAL_DISTANCE
     *
     * @return the value of tb_natmeha_hospital.HOSPITAL_DISTANCE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public Integer getHospitalDistance() {
        return hospitalDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_hospital.HOSPITAL_DISTANCE
     *
     * @param hospitalDistance the value for tb_natmeha_hospital.HOSPITAL_DISTANCE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setHospitalDistance(Integer hospitalDistance) {
        this.hospitalDistance = hospitalDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_hospital.HOSPITAL_PHONE
     *
     * @return the value of tb_natmeha_hospital.HOSPITAL_PHONE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getHospitalPhone() {
        return hospitalPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_hospital.HOSPITAL_PHONE
     *
     * @param hospitalPhone the value for tb_natmeha_hospital.HOSPITAL_PHONE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setHospitalPhone(String hospitalPhone) {
        this.hospitalPhone = hospitalPhone == null ? null : hospitalPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_hospital.HOSPITAL_PRO
     *
     * @return the value of tb_natmeha_hospital.HOSPITAL_PRO
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getHospitalPro() {
        return hospitalPro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_hospital.HOSPITAL_PRO
     *
     * @param hospitalPro the value for tb_natmeha_hospital.HOSPITAL_PRO
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setHospitalPro(String hospitalPro) {
        this.hospitalPro = hospitalPro == null ? null : hospitalPro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_hospital.HOSPITAL_CITY
     *
     * @return the value of tb_natmeha_hospital.HOSPITAL_CITY
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getHospitalCity() {
        return hospitalCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_hospital.HOSPITAL_CITY
     *
     * @param hospitalCity the value for tb_natmeha_hospital.HOSPITAL_CITY
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setHospitalCity(String hospitalCity) {
        this.hospitalCity = hospitalCity == null ? null : hospitalCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_hospital.HOSPITAL_COUNTRY
     *
     * @return the value of tb_natmeha_hospital.HOSPITAL_COUNTRY
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getHospitalCountry() {
        return hospitalCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_hospital.HOSPITAL_COUNTRY
     *
     * @param hospitalCountry the value for tb_natmeha_hospital.HOSPITAL_COUNTRY
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setHospitalCountry(String hospitalCountry) {
        this.hospitalCountry = hospitalCountry == null ? null : hospitalCountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_hospital.HOSPITAL_ADRESS
     *
     * @return the value of tb_natmeha_hospital.HOSPITAL_ADRESS
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getHospitalAdress() {
        return hospitalAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_hospital.HOSPITAL_ADRESS
     *
     * @param hospitalAdress the value for tb_natmeha_hospital.HOSPITAL_ADRESS
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setHospitalAdress(String hospitalAdress) {
        this.hospitalAdress = hospitalAdress == null ? null : hospitalAdress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_hospital.CREATER
     *
     * @return the value of tb_natmeha_hospital.CREATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_hospital.CREATER
     *
     * @param creater the value for tb_natmeha_hospital.CREATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_hospital.itemCreateAt
     *
     * @return the value of tb_natmeha_hospital.itemCreateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public Date getItemcreateat() {
        return itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_hospital.itemCreateAt
     *
     * @param itemcreateat the value for tb_natmeha_hospital.itemCreateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setItemcreateat(Date itemcreateat) {
        this.itemcreateat = itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_hospital.UPDATER
     *
     * @return the value of tb_natmeha_hospital.UPDATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_hospital.UPDATER
     *
     * @param updater the value for tb_natmeha_hospital.UPDATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_hospital.itemUpdateAt
     *
     * @return the value of tb_natmeha_hospital.itemUpdateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public Date getItemupdateat() {
        return itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_hospital.itemUpdateAt
     *
     * @param itemupdateat the value for tb_natmeha_hospital.itemUpdateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setItemupdateat(Date itemupdateat) {
        this.itemupdateat = itemupdateat;
    }
}