package com.gythtglxt.dataobject;

import java.util.Date;

public class HotspotDO extends HotspotDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_hotspot.HOTSPOT_TITLE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String hotspotTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_hotspot.DATA_STATUS
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String dataStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_hotspot.DATA_TYPE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String dataType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_hotspot.USER_CODE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_hotspot.CREATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_hotspot.itemCreateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private Date itemcreateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_hotspot.UPDATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_hotspot.itemUpdateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private Date itemupdateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_hotspot.HOTSPOT_CONTENT
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String hotspotContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_hotspot.HOTSPOT_TITLE
     *
     * @return the value of tb_natmeha_hotspot.HOTSPOT_TITLE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getHotspotTitle() {
        return hotspotTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_hotspot.HOTSPOT_TITLE
     *
     * @param hotspotTitle the value for tb_natmeha_hotspot.HOTSPOT_TITLE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setHotspotTitle(String hotspotTitle) {
        this.hotspotTitle = hotspotTitle == null ? null : hotspotTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_hotspot.DATA_STATUS
     *
     * @return the value of tb_natmeha_hotspot.DATA_STATUS
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getDataStatus() {
        return dataStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_hotspot.DATA_STATUS
     *
     * @param dataStatus the value for tb_natmeha_hotspot.DATA_STATUS
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setDataStatus(String dataStatus) {
        this.dataStatus = dataStatus == null ? null : dataStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_hotspot.DATA_TYPE
     *
     * @return the value of tb_natmeha_hotspot.DATA_TYPE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_hotspot.DATA_TYPE
     *
     * @param dataType the value for tb_natmeha_hotspot.DATA_TYPE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setDataType(String dataType) {
        this.dataType = dataType == null ? null : dataType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_hotspot.USER_CODE
     *
     * @return the value of tb_natmeha_hotspot.USER_CODE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_hotspot.USER_CODE
     *
     * @param userCode the value for tb_natmeha_hotspot.USER_CODE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_hotspot.CREATER
     *
     * @return the value of tb_natmeha_hotspot.CREATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_hotspot.CREATER
     *
     * @param creater the value for tb_natmeha_hotspot.CREATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_hotspot.itemCreateAt
     *
     * @return the value of tb_natmeha_hotspot.itemCreateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public Date getItemcreateat() {
        return itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_hotspot.itemCreateAt
     *
     * @param itemcreateat the value for tb_natmeha_hotspot.itemCreateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setItemcreateat(Date itemcreateat) {
        this.itemcreateat = itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_hotspot.UPDATER
     *
     * @return the value of tb_natmeha_hotspot.UPDATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_hotspot.UPDATER
     *
     * @param updater the value for tb_natmeha_hotspot.UPDATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_hotspot.itemUpdateAt
     *
     * @return the value of tb_natmeha_hotspot.itemUpdateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public Date getItemupdateat() {
        return itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_hotspot.itemUpdateAt
     *
     * @param itemupdateat the value for tb_natmeha_hotspot.itemUpdateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setItemupdateat(Date itemupdateat) {
        this.itemupdateat = itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_hotspot.HOTSPOT_CONTENT
     *
     * @return the value of tb_natmeha_hotspot.HOTSPOT_CONTENT
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getHotspotContent() {
        return hotspotContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_hotspot.HOTSPOT_CONTENT
     *
     * @param hotspotContent the value for tb_natmeha_hotspot.HOTSPOT_CONTENT
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setHotspotContent(String hotspotContent) {
        this.hotspotContent = hotspotContent == null ? null : hotspotContent.trim();
    }
}