package com.gythtglxt.dataobject;

import java.util.Date;

public class InteTreatDO extends InteTreatDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_inte_treat.GENDER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_inte_treat.BIRTH
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private Date birth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_inte_treat.DISCOMFORT_SITE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String discomfortSite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_inte_treat.SYMPTOM
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String symptom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_inte_treat.DESCRIBE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String describe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_inte_treat.POSITION
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_inte_treat.STATUS
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_inte_treat.USER_CODE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_inte_treat.CREATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_inte_treat.itemCreateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private Date itemcreateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_inte_treat.UPDATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_inte_treat.itemUpdateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private Date itemupdateat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_inte_treat.GENDER
     *
     * @return the value of tb_natmeha_inte_treat.GENDER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_inte_treat.GENDER
     *
     * @param gender the value for tb_natmeha_inte_treat.GENDER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_inte_treat.BIRTH
     *
     * @return the value of tb_natmeha_inte_treat.BIRTH
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_inte_treat.BIRTH
     *
     * @param birth the value for tb_natmeha_inte_treat.BIRTH
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_inte_treat.DISCOMFORT_SITE
     *
     * @return the value of tb_natmeha_inte_treat.DISCOMFORT_SITE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getDiscomfortSite() {
        return discomfortSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_inte_treat.DISCOMFORT_SITE
     *
     * @param discomfortSite the value for tb_natmeha_inte_treat.DISCOMFORT_SITE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setDiscomfortSite(String discomfortSite) {
        this.discomfortSite = discomfortSite == null ? null : discomfortSite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_inte_treat.SYMPTOM
     *
     * @return the value of tb_natmeha_inte_treat.SYMPTOM
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getSymptom() {
        return symptom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_inte_treat.SYMPTOM
     *
     * @param symptom the value for tb_natmeha_inte_treat.SYMPTOM
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setSymptom(String symptom) {
        this.symptom = symptom == null ? null : symptom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_inte_treat.DESCRIBE
     *
     * @return the value of tb_natmeha_inte_treat.DESCRIBE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_inte_treat.DESCRIBE
     *
     * @param describe the value for tb_natmeha_inte_treat.DESCRIBE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_inte_treat.POSITION
     *
     * @return the value of tb_natmeha_inte_treat.POSITION
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_inte_treat.POSITION
     *
     * @param position the value for tb_natmeha_inte_treat.POSITION
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_inte_treat.STATUS
     *
     * @return the value of tb_natmeha_inte_treat.STATUS
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_inte_treat.STATUS
     *
     * @param status the value for tb_natmeha_inte_treat.STATUS
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_inte_treat.USER_CODE
     *
     * @return the value of tb_natmeha_inte_treat.USER_CODE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_inte_treat.USER_CODE
     *
     * @param userCode the value for tb_natmeha_inte_treat.USER_CODE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_inte_treat.CREATER
     *
     * @return the value of tb_natmeha_inte_treat.CREATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_inte_treat.CREATER
     *
     * @param creater the value for tb_natmeha_inte_treat.CREATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_inte_treat.itemCreateAt
     *
     * @return the value of tb_natmeha_inte_treat.itemCreateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public Date getItemcreateat() {
        return itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_inte_treat.itemCreateAt
     *
     * @param itemcreateat the value for tb_natmeha_inte_treat.itemCreateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setItemcreateat(Date itemcreateat) {
        this.itemcreateat = itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_inte_treat.UPDATER
     *
     * @return the value of tb_natmeha_inte_treat.UPDATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_inte_treat.UPDATER
     *
     * @param updater the value for tb_natmeha_inte_treat.UPDATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_inte_treat.itemUpdateAt
     *
     * @return the value of tb_natmeha_inte_treat.itemUpdateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public Date getItemupdateat() {
        return itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_inte_treat.itemUpdateAt
     *
     * @param itemupdateat the value for tb_natmeha_inte_treat.itemUpdateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setItemupdateat(Date itemupdateat) {
        this.itemupdateat = itemupdateat;
    }
}