package com.gythtglxt.dataobject;

import java.util.Date;

public class MedRecordsDO extends MedRecordsDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_med_records.REGISTER_CODE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String registerCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_med_records.DISEASE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String disease;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_med_records.DIAGNOSIS
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String diagnosis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_med_records.ADVICE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String advice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_med_records.CREATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_med_records.itemCreateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private Date itemcreateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_med_records.UPDATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_med_records.itemUpdateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private Date itemupdateat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_med_records.REGISTER_CODE
     *
     * @return the value of tb_natmeha_med_records.REGISTER_CODE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getRegisterCode() {
        return registerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_med_records.REGISTER_CODE
     *
     * @param registerCode the value for tb_natmeha_med_records.REGISTER_CODE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setRegisterCode(String registerCode) {
        this.registerCode = registerCode == null ? null : registerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_med_records.DISEASE
     *
     * @return the value of tb_natmeha_med_records.DISEASE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getDisease() {
        return disease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_med_records.DISEASE
     *
     * @param disease the value for tb_natmeha_med_records.DISEASE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setDisease(String disease) {
        this.disease = disease == null ? null : disease.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_med_records.DIAGNOSIS
     *
     * @return the value of tb_natmeha_med_records.DIAGNOSIS
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getDiagnosis() {
        return diagnosis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_med_records.DIAGNOSIS
     *
     * @param diagnosis the value for tb_natmeha_med_records.DIAGNOSIS
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setDiagnosis(String diagnosis) {
        this.diagnosis = diagnosis == null ? null : diagnosis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_med_records.ADVICE
     *
     * @return the value of tb_natmeha_med_records.ADVICE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getAdvice() {
        return advice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_med_records.ADVICE
     *
     * @param advice the value for tb_natmeha_med_records.ADVICE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setAdvice(String advice) {
        this.advice = advice == null ? null : advice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_med_records.CREATER
     *
     * @return the value of tb_natmeha_med_records.CREATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_med_records.CREATER
     *
     * @param creater the value for tb_natmeha_med_records.CREATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_med_records.itemCreateAt
     *
     * @return the value of tb_natmeha_med_records.itemCreateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public Date getItemcreateat() {
        return itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_med_records.itemCreateAt
     *
     * @param itemcreateat the value for tb_natmeha_med_records.itemCreateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setItemcreateat(Date itemcreateat) {
        this.itemcreateat = itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_med_records.UPDATER
     *
     * @return the value of tb_natmeha_med_records.UPDATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_med_records.UPDATER
     *
     * @param updater the value for tb_natmeha_med_records.UPDATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_med_records.itemUpdateAt
     *
     * @return the value of tb_natmeha_med_records.itemUpdateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public Date getItemupdateat() {
        return itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_med_records.itemUpdateAt
     *
     * @param itemupdateat the value for tb_natmeha_med_records.itemUpdateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setItemupdateat(Date itemupdateat) {
        this.itemupdateat = itemupdateat;
    }
}