package com.gythtglxt.dataobject;

import java.util.Date;

public class PatientDO extends PatientDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_patient.PATIENT_NAME
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    private String patientName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_patient.GENDER
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_patient.BIRTHDATE
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    private Date birthdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_patient.IDCARD_TYPE
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    private String idcardType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_patient.IDCARD_NO
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    private String idcardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_patient.PHONE
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_patient.RELATIONSHIP
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    private String relationship;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_patient.DEFAULT_PATIENT
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    private String defaultPatient;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_patient.ADRESS_PRO
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    private String adressPro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_patient.ADRESS_CITY
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    private String adressCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_patient.ADRESS_COUNTRY
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    private String adressCountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_patient.ADRESS
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    private String adress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_patient.MARITAL_STATUS
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    private String maritalStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_patient.USER_CODE
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    private String userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_patient.CREATER
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_patient.itemCreateAt
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    private Date itemcreateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_patient.UPDATER
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_patient.itemUpdateAt
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    private Date itemupdateat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_patient.PATIENT_NAME
     *
     * @return the value of tb_natmeha_patient.PATIENT_NAME
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_patient.PATIENT_NAME
     *
     * @param patientName the value for tb_natmeha_patient.PATIENT_NAME
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName == null ? null : patientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_patient.GENDER
     *
     * @return the value of tb_natmeha_patient.GENDER
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_patient.GENDER
     *
     * @param gender the value for tb_natmeha_patient.GENDER
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_patient.BIRTHDATE
     *
     * @return the value of tb_natmeha_patient.BIRTHDATE
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public Date getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_patient.BIRTHDATE
     *
     * @param birthdate the value for tb_natmeha_patient.BIRTHDATE
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_patient.IDCARD_TYPE
     *
     * @return the value of tb_natmeha_patient.IDCARD_TYPE
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public String getIdcardType() {
        return idcardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_patient.IDCARD_TYPE
     *
     * @param idcardType the value for tb_natmeha_patient.IDCARD_TYPE
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public void setIdcardType(String idcardType) {
        this.idcardType = idcardType == null ? null : idcardType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_patient.IDCARD_NO
     *
     * @return the value of tb_natmeha_patient.IDCARD_NO
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public String getIdcardNo() {
        return idcardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_patient.IDCARD_NO
     *
     * @param idcardNo the value for tb_natmeha_patient.IDCARD_NO
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public void setIdcardNo(String idcardNo) {
        this.idcardNo = idcardNo == null ? null : idcardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_patient.PHONE
     *
     * @return the value of tb_natmeha_patient.PHONE
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_patient.PHONE
     *
     * @param phone the value for tb_natmeha_patient.PHONE
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_patient.RELATIONSHIP
     *
     * @return the value of tb_natmeha_patient.RELATIONSHIP
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public String getRelationship() {
        return relationship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_patient.RELATIONSHIP
     *
     * @param relationship the value for tb_natmeha_patient.RELATIONSHIP
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public void setRelationship(String relationship) {
        this.relationship = relationship == null ? null : relationship.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_patient.DEFAULT_PATIENT
     *
     * @return the value of tb_natmeha_patient.DEFAULT_PATIENT
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public String getDefaultPatient() {
        return defaultPatient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_patient.DEFAULT_PATIENT
     *
     * @param defaultPatient the value for tb_natmeha_patient.DEFAULT_PATIENT
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public void setDefaultPatient(String defaultPatient) {
        this.defaultPatient = defaultPatient == null ? null : defaultPatient.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_patient.ADRESS_PRO
     *
     * @return the value of tb_natmeha_patient.ADRESS_PRO
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public String getAdressPro() {
        return adressPro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_patient.ADRESS_PRO
     *
     * @param adressPro the value for tb_natmeha_patient.ADRESS_PRO
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public void setAdressPro(String adressPro) {
        this.adressPro = adressPro == null ? null : adressPro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_patient.ADRESS_CITY
     *
     * @return the value of tb_natmeha_patient.ADRESS_CITY
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public String getAdressCity() {
        return adressCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_patient.ADRESS_CITY
     *
     * @param adressCity the value for tb_natmeha_patient.ADRESS_CITY
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public void setAdressCity(String adressCity) {
        this.adressCity = adressCity == null ? null : adressCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_patient.ADRESS_COUNTRY
     *
     * @return the value of tb_natmeha_patient.ADRESS_COUNTRY
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public String getAdressCountry() {
        return adressCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_patient.ADRESS_COUNTRY
     *
     * @param adressCountry the value for tb_natmeha_patient.ADRESS_COUNTRY
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public void setAdressCountry(String adressCountry) {
        this.adressCountry = adressCountry == null ? null : adressCountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_patient.ADRESS
     *
     * @return the value of tb_natmeha_patient.ADRESS
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public String getAdress() {
        return adress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_patient.ADRESS
     *
     * @param adress the value for tb_natmeha_patient.ADRESS
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public void setAdress(String adress) {
        this.adress = adress == null ? null : adress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_patient.MARITAL_STATUS
     *
     * @return the value of tb_natmeha_patient.MARITAL_STATUS
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public String getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_patient.MARITAL_STATUS
     *
     * @param maritalStatus the value for tb_natmeha_patient.MARITAL_STATUS
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus == null ? null : maritalStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_patient.USER_CODE
     *
     * @return the value of tb_natmeha_patient.USER_CODE
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_patient.USER_CODE
     *
     * @param userCode the value for tb_natmeha_patient.USER_CODE
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_patient.CREATER
     *
     * @return the value of tb_natmeha_patient.CREATER
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_patient.CREATER
     *
     * @param creater the value for tb_natmeha_patient.CREATER
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_patient.itemCreateAt
     *
     * @return the value of tb_natmeha_patient.itemCreateAt
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public Date getItemcreateat() {
        return itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_patient.itemCreateAt
     *
     * @param itemcreateat the value for tb_natmeha_patient.itemCreateAt
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public void setItemcreateat(Date itemcreateat) {
        this.itemcreateat = itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_patient.UPDATER
     *
     * @return the value of tb_natmeha_patient.UPDATER
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_patient.UPDATER
     *
     * @param updater the value for tb_natmeha_patient.UPDATER
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_patient.itemUpdateAt
     *
     * @return the value of tb_natmeha_patient.itemUpdateAt
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public Date getItemupdateat() {
        return itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_patient.itemUpdateAt
     *
     * @param itemupdateat the value for tb_natmeha_patient.itemUpdateAt
     *
     * @mbg.generated Fri Nov 27 12:18:57 CST 2020
     */
    public void setItemupdateat(Date itemupdateat) {
        this.itemupdateat = itemupdateat;
    }
}