package com.gythtglxt.dataobject;

import java.util.Date;

public class ProjectDO extends ProjectDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_project.NAME
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_project.DATA_TYPE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String dataType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_project.PRICE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_project.DATA_STATUS
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String dataStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_project.USER_CODE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_project.VISIT_NUM
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private Integer visitNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_project.CREATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_project.itemCreateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private Date itemcreateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_project.UPDATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_project.itemUpdateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private Date itemupdateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_project.CONTENT
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_project.NAME
     *
     * @return the value of tb_natmeha_project.NAME
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_project.NAME
     *
     * @param name the value for tb_natmeha_project.NAME
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_project.DATA_TYPE
     *
     * @return the value of tb_natmeha_project.DATA_TYPE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_project.DATA_TYPE
     *
     * @param dataType the value for tb_natmeha_project.DATA_TYPE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setDataType(String dataType) {
        this.dataType = dataType == null ? null : dataType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_project.PRICE
     *
     * @return the value of tb_natmeha_project.PRICE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_project.PRICE
     *
     * @param price the value for tb_natmeha_project.PRICE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_project.DATA_STATUS
     *
     * @return the value of tb_natmeha_project.DATA_STATUS
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getDataStatus() {
        return dataStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_project.DATA_STATUS
     *
     * @param dataStatus the value for tb_natmeha_project.DATA_STATUS
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setDataStatus(String dataStatus) {
        this.dataStatus = dataStatus == null ? null : dataStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_project.USER_CODE
     *
     * @return the value of tb_natmeha_project.USER_CODE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_project.USER_CODE
     *
     * @param userCode the value for tb_natmeha_project.USER_CODE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_project.VISIT_NUM
     *
     * @return the value of tb_natmeha_project.VISIT_NUM
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public Integer getVisitNum() {
        return visitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_project.VISIT_NUM
     *
     * @param visitNum the value for tb_natmeha_project.VISIT_NUM
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setVisitNum(Integer visitNum) {
        this.visitNum = visitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_project.CREATER
     *
     * @return the value of tb_natmeha_project.CREATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_project.CREATER
     *
     * @param creater the value for tb_natmeha_project.CREATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_project.itemCreateAt
     *
     * @return the value of tb_natmeha_project.itemCreateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public Date getItemcreateat() {
        return itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_project.itemCreateAt
     *
     * @param itemcreateat the value for tb_natmeha_project.itemCreateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setItemcreateat(Date itemcreateat) {
        this.itemcreateat = itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_project.UPDATER
     *
     * @return the value of tb_natmeha_project.UPDATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_project.UPDATER
     *
     * @param updater the value for tb_natmeha_project.UPDATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_project.itemUpdateAt
     *
     * @return the value of tb_natmeha_project.itemUpdateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public Date getItemupdateat() {
        return itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_project.itemUpdateAt
     *
     * @param itemupdateat the value for tb_natmeha_project.itemUpdateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setItemupdateat(Date itemupdateat) {
        this.itemupdateat = itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_project.CONTENT
     *
     * @return the value of tb_natmeha_project.CONTENT
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_project.CONTENT
     *
     * @param content the value for tb_natmeha_project.CONTENT
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}