package com.gythtglxt.dataobject;

import java.util.Date;

public class SignalSourceDO extends SignalSourceDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_signal_source.DOCTOR_CODE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String doctorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_signal_source.REGISTER_TYPE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String registerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_signal_source.REGISTER_DATE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private Date registerDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_signal_source.STATUS
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_signal_source.USER_CODE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_signal_source.CREATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_signal_source.itemCreateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private Date itemcreateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_signal_source.UPDATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_natmeha_signal_source.itemUpdateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    private Date itemupdateat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_signal_source.DOCTOR_CODE
     *
     * @return the value of tb_natmeha_signal_source.DOCTOR_CODE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getDoctorCode() {
        return doctorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_signal_source.DOCTOR_CODE
     *
     * @param doctorCode the value for tb_natmeha_signal_source.DOCTOR_CODE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setDoctorCode(String doctorCode) {
        this.doctorCode = doctorCode == null ? null : doctorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_signal_source.REGISTER_TYPE
     *
     * @return the value of tb_natmeha_signal_source.REGISTER_TYPE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getRegisterType() {
        return registerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_signal_source.REGISTER_TYPE
     *
     * @param registerType the value for tb_natmeha_signal_source.REGISTER_TYPE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setRegisterType(String registerType) {
        this.registerType = registerType == null ? null : registerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_signal_source.REGISTER_DATE
     *
     * @return the value of tb_natmeha_signal_source.REGISTER_DATE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_signal_source.REGISTER_DATE
     *
     * @param registerDate the value for tb_natmeha_signal_source.REGISTER_DATE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_signal_source.STATUS
     *
     * @return the value of tb_natmeha_signal_source.STATUS
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_signal_source.STATUS
     *
     * @param status the value for tb_natmeha_signal_source.STATUS
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_signal_source.USER_CODE
     *
     * @return the value of tb_natmeha_signal_source.USER_CODE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_signal_source.USER_CODE
     *
     * @param userCode the value for tb_natmeha_signal_source.USER_CODE
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_signal_source.CREATER
     *
     * @return the value of tb_natmeha_signal_source.CREATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_signal_source.CREATER
     *
     * @param creater the value for tb_natmeha_signal_source.CREATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_signal_source.itemCreateAt
     *
     * @return the value of tb_natmeha_signal_source.itemCreateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public Date getItemcreateat() {
        return itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_signal_source.itemCreateAt
     *
     * @param itemcreateat the value for tb_natmeha_signal_source.itemCreateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setItemcreateat(Date itemcreateat) {
        this.itemcreateat = itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_signal_source.UPDATER
     *
     * @return the value of tb_natmeha_signal_source.UPDATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_signal_source.UPDATER
     *
     * @param updater the value for tb_natmeha_signal_source.UPDATER
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_natmeha_signal_source.itemUpdateAt
     *
     * @return the value of tb_natmeha_signal_source.itemUpdateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public Date getItemupdateat() {
        return itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_natmeha_signal_source.itemUpdateAt
     *
     * @param itemupdateat the value for tb_natmeha_signal_source.itemUpdateAt
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    public void setItemupdateat(Date itemupdateat) {
        this.itemupdateat = itemupdateat;
    }
}