package com.gythtglxt.dao;

import com.gythtglxt.dataobject.HealthRecordsDO;
import com.gythtglxt.dataobject.HealthRecordsDOKey;

public interface HealthRecordsDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_health_records
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int deleteByPrimaryKey(HealthRecordsDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_health_records
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int insert(HealthRecordsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_health_records
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int insertSelective(HealthRecordsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_health_records
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    HealthRecordsDO selectByPrimaryKey(HealthRecordsDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_health_records
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int updateByPrimaryKeySelective(HealthRecordsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_health_records
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int updateByPrimaryKey(HealthRecordsDO record);
}