package com.gythtglxt.dao;

import com.gythtglxt.dataobject.HospitalDO;
import com.gythtglxt.dataobject.HospitalDOKey;

public interface HospitalDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_hospital
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int deleteByPrimaryKey(HospitalDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_hospital
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int insert(HospitalDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_hospital
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int insertSelective(HospitalDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_hospital
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    HospitalDO selectByPrimaryKey(HospitalDOKey key);

    HospitalDO selectByHospitalName(String hospiyalName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_hospital
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int updateByPrimaryKeySelective(HospitalDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_hospital
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int updateByPrimaryKey(HospitalDO record);

}
