package com.gythtglxt.dao;

import com.gythtglxt.dataobject.HotsCollRefDO;
import com.gythtglxt.dataobject.HotsCollRefDOKey;

public interface HotsCollRefDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_hots_coll_ref
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int deleteByPrimaryKey(HotsCollRefDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_hots_coll_ref
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int insert(HotsCollRefDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_hots_coll_ref
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int insertSelective(HotsCollRefDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_hots_coll_ref
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    HotsCollRefDO selectByPrimaryKey(HotsCollRefDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_hots_coll_ref
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int updateByPrimaryKeySelective(HotsCollRefDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_hots_coll_ref
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int updateByPrimaryKey(HotsCollRefDO record);
}