package com.gythtglxt.dao;

import com.gythtglxt.dataobject.InteTreatDO;
import com.gythtglxt.dataobject.InteTreatDOKey;

public interface InteTreatDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_inte_treat
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int deleteByPrimaryKey(InteTreatDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_inte_treat
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int insert(InteTreatDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_inte_treat
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int insertSelective(InteTreatDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_inte_treat
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    InteTreatDO selectByPrimaryKey(InteTreatDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_inte_treat
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int updateByPrimaryKeySelective(InteTreatDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_inte_treat
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int updateByPrimaryKey(InteTreatDO record);
}