package com.gythtglxt.dao;

import com.gythtglxt.dataobject.MedCostDO;
import com.gythtglxt.dataobject.MedCostDOKey;

public interface MedCostDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_med_cost
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int deleteByPrimaryKey(MedCostDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_med_cost
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int insert(MedCostDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_med_cost
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int insertSelective(MedCostDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_med_cost
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    MedCostDO selectByPrimaryKey(MedCostDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_med_cost
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int updateByPrimaryKeySelective(MedCostDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_med_cost
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int updateByPrimaryKey(MedCostDO record);
}