package com.gythtglxt.dao;

import com.gythtglxt.dataobject.PatientDO;
import com.gythtglxt.dataobject.PatientDOKey;

public interface PatientDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_patient
     *
     * @mbg.generated Thu Nov 26 16:08:38 CST 2020
     */
    int deleteByPrimaryKey(PatientDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_patient
     *
     * @mbg.generated Thu Nov 26 16:08:38 CST 2020
     */
    int insert(PatientDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_patient
     *
     * @mbg.generated Thu Nov 26 16:08:38 CST 2020
     */
    int insertSelective(PatientDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_patient
     *
     * @mbg.generated Thu Nov 26 16:08:38 CST 2020
     */
    PatientDO selectByPrimaryKey(PatientDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_patient
     *
     * @mbg.generated Thu Nov 26 16:08:38 CST 2020
     */
    int updateByPrimaryKeySelective(PatientDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_patient
     *
     * @mbg.generated Thu Nov 26 16:08:38 CST 2020
     */
    int updateByPrimaryKey(PatientDO record);
}