package com.gythtglxt.dao;

import com.gythtglxt.dataobject.RegisterRefDO;
import com.gythtglxt.dataobject.RegisterRefDOKey;

public interface RegisterRefDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_register_ref
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int deleteByPrimaryKey(RegisterRefDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_register_ref
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int insert(RegisterRefDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_register_ref
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int insertSelective(RegisterRefDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_register_ref
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    RegisterRefDO selectByPrimaryKey(RegisterRefDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_register_ref
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int updateByPrimaryKeySelective(RegisterRefDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_register_ref
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int updateByPrimaryKey(RegisterRefDO record);
}