package com.gythtglxt.dao;

import com.gythtglxt.dataobject.ResourceDO;
import com.gythtglxt.dataobject.ResourceDOKey;

public interface ResourceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    int deleteByPrimaryKey(ResourceDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    int insert(ResourceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    int insertSelective(ResourceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    ResourceDO selectByPrimaryKey(ResourceDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    int updateByPrimaryKeySelective(ResourceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Thu Nov 26 12:29:36 CST 2020
     */
    int updateByPrimaryKey(ResourceDO record);
}