package com.gythtglxt.dao;

import com.gythtglxt.dataobject.ResourceRoleRefDO;
import com.gythtglxt.dataobject.ResourceRoleRefDOKey;

public interface ResourceRoleRefDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_role_ref
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int deleteByPrimaryKey(ResourceRoleRefDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_role_ref
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int insert(ResourceRoleRefDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_role_ref
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int insertSelective(ResourceRoleRefDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_role_ref
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    ResourceRoleRefDO selectByPrimaryKey(ResourceRoleRefDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_role_ref
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int updateByPrimaryKeySelective(ResourceRoleRefDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_role_ref
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int updateByPrimaryKey(ResourceRoleRefDO record);
}