package com.gythtglxt.dao;

import com.gythtglxt.dataobject.SignalSourceDO;
import com.gythtglxt.dataobject.SignalSourceDOKey;

public interface SignalSourceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_signal_source
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int deleteByPrimaryKey(SignalSourceDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_signal_source
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int insert(SignalSourceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_signal_source
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int insertSelective(SignalSourceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_signal_source
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    SignalSourceDO selectByPrimaryKey(SignalSourceDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_signal_source
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int updateByPrimaryKeySelective(SignalSourceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_natmeha_signal_source
     *
     * @mbg.generated Thu Nov 26 00:22:00 CST 2020
     */
    int updateByPrimaryKey(SignalSourceDO record);
}